version: '2'
services:
  datastore:
    container_name: senpai_mento_datastore
    image: busybox
    volumes:
      - mysql_data:/var/lib/mysql/data
      - node_modules:/app/node_modules
      
  api:
    container_name: senpai_mento_api
    build:
      context: . 
      dockerfile: docker/node/Dockerfile
    command: docker/node/start.sh
    depends_on:
      - db
    ports:
      - '3000:3000'
    environment:
      DB_HOST: db
      NODE_ENV: development
    networks:
      - default
    stdin_open: true
    tty: true
    volumes:
      - .:/app
    volumes_from:
      - datastore
  
  db:
    container_name: senpai_mento_mysql
    build: 
      context: . 
      dockerfile: docker/mysql/Dockerfile
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    environment: # CAUTION: 本番環境ではROOTの設定をする。githubのmysql-docker参照
      MYSQL_USER: mysql
      MYSQL_PASSWORD: mysql
    networks:
      - default
    ports:
      - '3306:3306'
    volumes_from:
      - datastore

volumes:
  mysql_data:
    driver: local
  node_modules:
    driver: local