version: '2'
services:
  datastore:
    container_name: senpai_mento_datastore
    image: busybox
    volumes:
      - mysql_data:/var/lib/mysql
      
  api:
    container_name: senpai_mento_api
    build:
      context: . 
      dockerfile: docker/node/Dockerfile
    command: docker/node/start.sh
    depends_on:
      - db
    ports:
      - '3000:3000'
    environment:
      DB_HOST: db
      NODE_ENV: development
    networks:
      - default
    stdin_open: true
    tty: true
    volumes:
      - .:/app
    volumes_from:
      - datastore
  
  db:
    container_name: senpai_mento_mysql
    image: mysql:5.6.39
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --explicit_defaults_for_timestamp=1
    environment:
      MYSQL_USER: mysql
      MYSQL_PASSWORD: mysql
      MYSQL_ROOT_PASSWORD: root
      LANG: ja_JP.UTF-8
    networks:
      - default
    ports:
      - '3306:3306'
    volumes_from:
      - datastore

volumes:
  mysql_data:
    driver: local